name: wallpiper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bmnav: ^0.3.4
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.18
  http: ^0.12.2
  flutter_staggered_grid_view: ^0.3.2
  url_launcher: ^5.7.2
  url_launcher_web: ^0.1.4+1
  image_gallery_saver: ^1.5.0
  permission_handler: ^5.0.1+1
  dio: ^3.0.10
  gallery_saver: ^2.0.1
  # wallpaper: ^1.0.4
  # network_to_file_image: ^2.3.5
  random_string: ^2.1.0
  shared_preferences: ^0.5.12
  provider: ^4.3.2+2
  dynamic_theme: ^1.0.1
  # wallpaper_manager: ^1.0.10
  # flutter_cache_manager: ^1.4.2
  # footer: ^0.0.3
  # persistent_bottom_nav_bar: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash.png
    - assets/splash2.png
    - assets/wallpiper.png
    - assets/no_connection.png
    - assets/categories/3D.jpeg
    - assets/categories/Abstract.jpeg
    - assets/categories/Alone.jpeg
    - assets/categories/Animals.jpeg
    - assets/categories/Anime.jpeg
    - assets/categories/art.jpeg
    - assets/categories/Black.jpeg
    - assets/categories/Cars.jpeg
    - assets/categories/City.jpeg
    - assets/categories/Drinks.jpeg
    - assets/categories/Entertainment.jpeg
    - assets/categories/Fantasy.jpeg
    - assets/categories/Flowers.jpeg
    - assets/categories/Food.jpeg
    - assets/categories/Holiday.jpeg
    - assets/categories/Macro.jpeg
    - assets/categories/Mask.jpeg
    - assets/categories/Motorcycles.jpeg
    - assets/categories/Music.jpeg
    - assets/categories/Nature.jpeg
    - assets/categories/Neon.jpeg
    - assets/categories/People.jpeg
    - assets/categories/Predator.jpeg
    - assets/categories/Smiles.jpeg
    - assets/categories/Space.jpeg
    - assets/categories/Sports.jpeg
    - assets/categories/Summer.jpeg
    - assets/categories/Technology.jpeg
    - assets/categories/Textures.jpeg
    - assets/categories/Vector.jpeg
    - assets/categories/Vehicles.jpeg
    - assets/categories/White.jpeg
    - assets/categories/Winter.jpeg
    - assets/categories/Words.jpeg
    - assets/categories/world.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
